[package]
name = "task_mngr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
chrono = {version = "0.4", features = ["serde"] }
